name: GitHub Actions Demo
on: [push]
jobs:
  yarn-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node14-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

  run-web:
    needs: npm-install
    runs-on: ubuntu-latest
    defaults:
       run:
          shell: bash
          working-directory: ./web
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node14-${{ hashFiles('**/yarn.lock') }}
      - name: List files in the repository
        run: |
          ls && cat index.js 
      - name: Run program
        run: |
          node index.js

  run-api:
    needs: npm-install
    runs-on: ubuntu-latest
    defaults:
       run:
          shell: bash
          working-directory: ./api
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node14-${{ hashFiles('**/yarn.lock') }}
      - name: List files in the repository
        run: |
          ls && cat index.js 
      - name: Run program
        run: |
          node index.js
